# Label Encoding & One-hot Encoding

As we know the input of the machine learning deals more with numbers and arrays rather than non-umeric problems. Therefore, one way of mapping the character values in machine learning into numerical ones is by using Label encoder. I covnerts the letters into integer numbers starting from 0 to the total number of classes. Suppose there are 3 classes in iris dtaset (setosa, versicolor, and verginica). These clases can be represented by 0,1, and 2 though Label Encoder.

In [8]:
#Lets creat a data frome with four columns
import pandas as pd
import numpy as np
df = pd.DataFrame([['green', 'M', 10.1, 'class1'],
                   ['red', 'L', 13.5, 'class2'],
                   ['blue', 'XL', 15.3, 'class1']] )

df.columns = ['color', 'size', 'price', 'classlabel']
df

color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1

In [9]:
#The features must be converted into numerical values before using any machine lerning algorithm. 
#Therefore, now lets change the size to numerical values.
size_mapping = {'XL': 3,
                'L': 2,
                'M': 1}

df['size'] = df['size'].map(size_mapping)
df

color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   blue     3   15.3     class1

In [10]:
#Now the classlabels column from the dataframe can be converted into the numerical format.
#One of the wat is we can achieve this by directly mapping the values to desired numbers.
class_mapping = {label: idx for idx, label in enumerate(np.unique(df['classlabel']))}
print(class_mapping)

df['classlabel'] = df['classlabel'].map(class_mapping) 
df

{'class1': 0, 'class2': 1}


color  size  price  classlabel
0  green     1   10.1           0
1    red     2   13.5           1
2   blue     3   15.3           0

In [11]:
#The next way to do the same thing in more automatic manner is to use the Labelencoder.
#The labelencoder can be imported from the scikit learn preprocessing library.
from sklearn.preprocessing import LabelEncoder
class_le = LabelEncoder()
y = class_le.fit_transform(df['classlabel'].values) # Fit_transform function for data transformation
y

array([0, 1, 0], dtype=int64)

Now since the labels are assigned to each classes: class1 with label 0, and class 2 with label 1.
In the next step we define our features, which are the values of remaining columns of our dataframe. i.e., color, size, and price

In [12]:
X = df[['color', 'size', 'price']].values
X

array([['green', 1, 10.1],
       ['red', 2, 13.5],
       ['blue', 3, 15.3]], dtype=object)

We can see that the out of three features, color feature has character values, so we need to convert it into numerical value. For this, we can again use label encoder and fit to the corresponding feature values.

In [13]:
color_le = LabelEncoder()
X[:, 0] = color_le.fit_transform(X[:, 0]) #fitting the transformation to all the rows of the 1st column.
X

array([[1, 1, 10.1],
       [2, 2, 13.5],
       [0, 3, 15.3]], dtype=object)

# One-hot Encoding

On-hot encoding allows to work with the categorical data. IF there are multiple categories/classes, then they can be converted into the numerical format by using one-hot encoder. The only bit that represents the class is TRUE i.e., 1, while the rest are set to FALSE, i.e., 0. Lets see an example of one-hot encoding below.

In [14]:
#we can use the onehotencoder function from the scikit learn library

from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categories = 'auto') #categorical_features=[0] to pass the column position of the property to the parameter
print(ohe.fit_transform(X).toarray()) #Returns a sparse matrix, so check the contents with the to array method
print(pd.get_dummies(df[['price', 'color', 'size']]))

[[0. 1. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1. 0. 0. 1.]]
   price  size  color_blue  color_green  color_red
0   10.1     1           0            1          0
1   13.5     2           0            0          1
2   15.3     3           1            0          0


In the above example, we can see that each color features are one hot encoded, which means that the 1st class (green) is categorically encoded to [1, 0, 0], second class (red) to [0, 1, 0], and the third class (blue) to [0, 0, 1].