# Data analysis with pandas - 02

In this example, we will learn how to check the null values in the dataframes. The null values in any data frame can be harmful for creating any models, thus it should be dropped i.e., removed, or filled with any other stochastic values. In this chapter we will learn about imputer which is a sckit learn library. To install scikit learn in your anaconda environmnet, please go to this link: https://scikit-learn.org/stable/install.html

In [1]:
import pandas as pd
from io import StringIO

The StringIO module an in-memory file-like object. This object can be used as input or output to the most function that would expect a standard file object

In [2]:
#creating a csv (comma separated values) data.
csv_data = '''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,11.0,12.0,'''

df = pd.read_csv(StringIO(csv_data))
df

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [3]:
#checking the null i.e., empty elements in the columns
df.isnull().sum()

A    0
B    0
C    1
D    1
dtype: int64

df.dropna : Determine if rows or columns which contain missing values are removed. 0, or ‘index’ : Drop rows which contain missing values. 1, or ‘columns’ : Drop columns which contain missing value

In [4]:
df.dropna(axis=1)

A     B
0   1.0   2.0
1   5.0   6.0
2  10.0  11.0

In [5]:
df.dropna(how = 'all')

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [6]:
df.dropna(thresh = 4)

A    B    C    D
0  1.0  2.0  3.0  4.0

In [7]:
df.dropna(subset = ['C'])

A     B     C    D
0   1.0   2.0   3.0  4.0
2  10.0  11.0  12.0  NaN

# Imputer example: 01

SimpleImputer is a scikit learn library that allows us to fill in the missing values. Details can be found here: https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html

In [8]:
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [10]:
df = pd.read_csv('data11_khan2-Copy1.csv')
df

V1        V2        V3        V4        V5        V6        V7  \
0   0.773344 -2.438405 -0.482562 -2.721135 -1.217058  0.827809  1.342604   
1  -0.078178 -2.415754  0.412772 -2.825146 -0.626236  0.054488  1.429498   
2  -0.084469 -1.649739 -0.241308 -2.875286 -0.889405 -0.027474  1.159300   
3   0.965614 -2.380547  0.625297 -1.741256 -0.845366  0.949687  1.093801   
4   0.075664 -1.728785  0.852626  0.272695 -1.841370  0.327936  1.251219   
..       ...       ...       ...       ...       ...       ...       ...   
58 -2.683846 -2.117767 -0.523236 -2.174192 -0.448947  0.543022  1.338731   
59 -1.207646 -2.478130  0.094310  0.273456 -1.113218 -0.283690  1.105985   
60 -1.684161 -2.053384  0.563835  0.314446 -2.052605 -0.630172  1.570967   
61 -2.258568 -2.308603 -1.443076  0.233094 -1.779633 -0.030665  1.532665   
62 -1.146333 -3.007805 -0.029326  0.237835 -2.859455  0.042293  1.318417   

          V8        V9       V10  ...       V91       V92       V93       V94  \
0   0.057042  0.133569  0.565427  ... -1.558745  0.255417 -3.717279  1.169226   
1  -0.120249  0.456792  0.159053  ... -1.738977 -0.299350 -3.381395  0.574138   
2   0.015676  0.191942  0.496585  ... -1.213014 -0.080560 -2.805112  0.532744   
3   0.819736 -0.284620  0.994732  ...  0.204898  0.502350 -2.289669  0.880788   
4   0.771450  0.030917  0.278313  ... -1.039589 -0.434791 -1.979053  1.004338   
..       ...       ...       ...  ...       ...       ...       ...       ...   
58  0.194250  0.599276  0.637370  ... -0.451300 -0.160521 -2.715075  1.424168   
59  0.801284  0.381582  0.714811  ... -0.161226 -0.296521 -2.325854  1.077014   
60  0.137324  1.036985  0.973654  ...  0.158285 -0.582859 -1.725972  1.139850   
61 -0.408419  0.795162  0.376242  ... -0.940840 -0.543865 -0.867739  1.357277   
62 -0.540426  0.183071  0.503438  ... -1.116267 -0.466649 -1.888491  1.452527   

         V95       V96       V97       V98       V99      V100  
0  -1.030019 -0.717235 -0.759501 -2.741090  0.200980 -2.338212  
1  -1.840740 -1.408949 -1.038741 -1.845793  0.617561 -2.289669  
2  -1.227924 -0.604404 -0.701381 -1.240291 -0.418550 -2.132842  
3  -1.166035 -0.319930 -0.558267 -1.348999  0.234914 -1.745258  
4  -1.009229 -0.166409 -0.605136 -1.325764  1.000963 -0.833790  
..       ...       ...       ...       ...       ...       ...  
58 -1.611941 -0.430168 -1.029739 -1.577455 -0.497909 -1.877317  
59 -1.654958 -0.155719  0.174625 -1.697177 -0.977103 -2.126953  
60 -1.753886 -0.253603 -0.141103 -2.306593 -0.412188 -1.276185  
61 -2.109488 -0.561067 -0.574476 -1.715354 -0.531198 -0.561768  
62 -2.158485 -0.750776 -0.416577 -2.051826 -1.142251 -1.483246  

[63 rows x 100 columns]

In [11]:
df.head #Returns the first n rows. Default is 5.

<bound method NDFrame.head of           V1        V2        V3        V4        V5        V6        V7  \
0   0.773344 -2.438405 -0.482562 -2.721135 -1.217058  0.827809  1.342604   
1  -0.078178 -2.415754  0.412772 -2.825146 -0.626236  0.054488  1.429498   
2  -0.084469 -1.649739 -0.241308 -2.875286 -0.889405 -0.027474  1.159300   
3   0.965614 -2.380547  0.625297 -1.741256 -0.845366  0.949687  1.093801   
4   0.075664 -1.728785  0.852626  0.272695 -1.841370  0.327936  1.251219   
..       ...       ...       ...       ...       ...       ...       ...   
58 -2.683846 -2.117767 -0.523236 -2.174192 -0.448947  0.543022  1.338731   
59 -1.207646 -2.478130  0.094310  0.273456 -1.113218 -0.283690  1.105985   
60 -1.684161 -2.053384  0.563835  0.314446 -2.052605 -0.630172  1.570967   
61 -2.258568 -2.308603 -1.443076  0.233094 -1.779633 -0.030665  1.532665   
62 -1.146333 -3.007805 -0.029326  0.237835 -2.859455  0.042293  1.318417   

          V8        V9       V10  ...       V91       V92

In [12]:
#Descriptive statistics include those 
#that summarize the central tendency, dispersion and shape of a dataset’s distribution, excluding NaN values.
#It calculates the all the percentiles including mean, and median of all the numerical values.
df.describe() 

V1         V2         V3         V4         V5         V6  \
count  63.000000  63.000000  63.000000  63.000000  63.000000  63.000000   
mean    0.146931  -1.739001  -0.248668  -1.078090  -1.385706   0.517289   
std     0.853339   0.905571   0.701464   1.190656   0.653898   0.661113   
min    -2.683846  -3.007805  -1.851509  -2.956512  -3.216379  -1.118101   
25%    -0.081323  -2.427079  -0.634168  -2.121514  -1.860178   0.086846   
50%     0.244200  -1.949818  -0.113617  -1.274395  -1.211669   0.542266   
75%     0.735390  -1.318730   0.253025   0.235544  -0.882397   0.944085   
max     1.285507   0.654770   1.160742   0.583779  -0.264747   2.452728   

              V7         V8         V9        V10  ...        V91        V92  \
count  63.000000  63.000000  63.000000  63.000000  ...  63.000000  63.000000   
mean    1.552154   0.095126   0.162019   0.345152  ...  -0.985032  -0.228647   
std     0.365211   0.488837   0.434185   0.520687  ...   0.654176   0.571298   
min     0.776063  -1.218072  -0.639227  -1.572142  ...  -2.051826  -1.461880   
25%     1.288394  -0.321716  -0.123633   0.052318  ...  -1.441956  -0.630263   
50%     1.510170   0.137324   0.133569   0.386554  ...  -1.057566  -0.294103   
75%     1.791493   0.437873   0.455650   0.693397  ...  -0.696169   0.246271   
max     2.864085   0.956626   1.255815   1.122492  ...   2.120308   0.804554   

             V93        V94        V95        V96        V97        V98  \
count  63.000000  63.000000  63.000000  63.000000  63.000000  63.000000   
mean   -1.921443   1.021578  -1.172988  -0.608294  -0.504219  -1.727577   
std     0.801627   0.370958   0.625335   0.399017   0.363740   0.610046   
min    -3.717279  -0.379651  -3.470547  -1.408949  -1.164111  -3.767923   
25%    -2.593227   0.823999  -1.562574  -0.940331  -0.754286  -2.052216   
50%    -1.951928   1.067569  -1.111090  -0.618968  -0.574476  -1.684161   
75%    -1.318936   1.238401  -0.786899  -0.285104  -0.252702  -1.396644   
max    -0.241435   2.007610   0.170924   0.516291   0.270485  -0.116759   

             V99       V100  
count  63.000000  63.000000  
mean    0.258184  -1.383372  
std     0.589139   0.587704  
min    -1.142251  -2.447611  
25%    -0.087088  -1.780104  
50%     0.234914  -1.365708  
75%     0.658667  -1.078854  
max     1.441776   0.449801  

[8 rows x 100 columns]

In [13]:
#df.values --> returns a Numpy representation of the DataFrame (the data frame is now in array format).
xorg = df.values
xorg

array([[ 0.77334372, -2.43840482, -0.48256216, ..., -2.74109005,
         0.20097974, -2.33821227],
       [-0.07817778, -2.41575379,  0.41277168, ..., -1.84579336,
         0.61756119, -2.28966887],
       [-0.08446916, -1.64973921, -0.24130752, ..., -1.24029107,
        -0.41855035, -2.13284232],
       ...,
       [-1.68416146, -2.05338401,  0.56383544, ..., -2.30659311,
        -0.41218765, -1.27618514],
       [-2.25856821, -2.30860317, -1.44307637, ..., -1.71535414,
        -0.53119841, -0.5617681 ],
       [-1.14633302, -3.00780485, -0.02932583, ..., -2.05182638,
        -1.14225075, -1.48324589]])

In [14]:
# Missing value detection
# NaN index extraction (True, False). To check the null values in the numpy array that we created in the previous
#step. The index of the null values are set to True, and false otherwise.
naidx = np.isnan(xorg) 
naidx

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [15]:
#Total sum of the null i.e., NaN values in the array.
naidx.sum()

43

In [16]:
#total number of NaN values in a single array 
abx = naidx.sum(axis = 1)
abx

array([1, 0, 3, 2, 1, 1, 0, 1, 0, 2, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       2, 0, 0, 0, 1, 0, 1, 0, 1, 2, 0, 0, 0, 2, 1, 0, 1, 0, 1, 0, 0, 2,
       2, 0, 0, 2, 1, 0, 0, 2, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1])

In [17]:
# simple missing value imputation
from sklearn.impute import SimpleImputer

f = SimpleImputer(missing_values=np.nan,strategy='mean')
xfill = f.fit_transform(xorg) 
np.isnan(xfill).sum() # Number of NaN indexes=0

0

In [18]:
xfill[naidx] # Check the filled value in the existing NaN location

array([ 1.54189923,  0.16718706, -1.11401465, -0.65789924, -0.30107029,
       -0.65789924, -0.30107029,  0.16718706, -1.57675201, -1.11401465,
       -1.57675201, -0.65789924, -1.57675201,  1.54189923, -1.57675201,
       -0.65789924,  0.5774776 ,  0.16718706,  0.5774776 ,  0.16718706,
       -1.11401465, -0.65789924,  1.54189923, -1.57675201,  0.5774776 ,
        0.16718706,  1.54189923, -0.30107029, -1.11401465,  0.16718706,
       -1.11401465, -0.30107029,  0.5774776 ,  0.16718706, -1.11401465,
        0.5774776 ,  0.16718706,  0.16718706,  0.5774776 ,  1.54189923,
        0.16718706, -0.30107029,  0.16718706])

In [19]:
f = SimpleImputer(missing_values=np.nan,strategy='constant',fill_value=0)
xfill = f.fit_transform(xorg) # Number of NaN indexes=0
xfill[naidx]  # Check the filled value in the existing NaN location

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])